# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Petmily' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Petmily
  pod 'Gifu'

  target 'PetmilyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetmilyUITests' do
    # Pods for testing
  end

end
