# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Petmily' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Petmily
  pod 'Gifu'
  pod 'KakaoMapsSDK', '2.6.3'

  target 'PetmilyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetmilyUITests' do
    # Pods for testing
  end

end
